### ISSUE TITLE
Automatic username changes

### ISSUE THREAD

**Issue by psikoi** [wise-old-man/wise-old-man#124]
Since Jagex doesn't provide us with any way of confirming a player's name changes, we gotta figure out a creative way to check for this.

So given the inputs:
```
{
  old: Psikoi
  new: Zezima
}
```

There's a few things we should check before deciding this name change is valid:

- "new" is on the hiscores
- "old" is NOT on the hiscores (is this required? It seems to be on CML)
- "new" has all higher or the same stats as "old"
- **requires EHP update** If the exp gained during the gap between the last snapshot of "old" and the first snapshot of "new" is not higher than EHP. (Check if the player hasn't gained 1000 hours worth of efficient exp in 16 hours)

I'm not sure these are sufficient to confidently automatically approve a name change, but should be good for atleast a manual confirmation system. Where I'd have to manually check every request and accept/deny based on the above conditions.

**Note:** A very important topic to discuss is, in case the player tracked the new username without requesting a name change first, what do we do with this new player account? do we delete it?

**Comment by dekvall** [comment]
The only reliable way i can think of is to use the forums for tracking name changes. And even then it won't be 100% correct if someone double name-changes between two cronjobs. Unfortunately this requires some manual set up that most casual players probably won't do.

Another thing we could use is 200m xp ranks to track namechanges, since these are static as long as someone higher up isn't banned. Which i think happens seldom, but there really isn't any foolproof way to automatically track this.

Using EHP like it's mentioned in the OP is a good idea but it requires players to register their namechange. Doing it automatically would be nice. If we implement the criteria listed above i don't think we would add much with a manual confirmation, we would just have to trust the system because honestly, we don't know much more than it does.

I think a player name needs to be available at least 30 days before a player can take that name, so i would like to add the criteria that a player with the new name cannot have been updated during the last 30 days, but if an user messes up and tracks their new account before submitting a name change, it would be rejected. But maybe we can do something smart, I don't know.

For the last topic:
I think snapshots of a player should be archived and the `Track this player` button should reappear for the username which no longer exist on the hiscores. Later on, when someone submits a namechange we should pull the archived snapshots and add them to the new name. Then again if a player have done multiple namechanges without registering, they would have to submit some kind of namechange chain to get their datapoints back.

**Comment by psikoi** [comment]
Depends on EHP, changing to low priority until ehp is handled

**Comment by psikoi** [comment]
Implemented in #371
