### ISSUE TITLE
Clear "reviewContext" when a name change gets approved

### ISSUE THREAD

**Issue by psikoi** [wise-old-man/wise-old-man#1392]
A `reviewContext` field is populated on name changes whenever they get auto-reviewed and skipped (for excessive gains, negative gains, etc).

The same name change can later be approved, but this doesn't clear this `reviewContext` column. And it should.

It seems that on `ApproveNameChangeService.ts (L70)` I did set this to undefined, but it should really be null. A integration test case should also be added to ensure this happens.

**Comment by derektolliver** [comment]
@psikoi Looking to address this one but I have some clarifying questions.

Right now I'm viewing the changes necessary here as:
1. Update L70 on `ApproveNameChangeService.ts` to be set to `null`
2. Implement an integration test in `server/__tests__/suites/integration/names.test.ts` to ensure `approveNameChange` updates `reviewContext` as `null` instead of `undefined`

Besides these, when you say:
> The same name change can later be approved, but this doesn't clear this reviewContext column. And it should.

Is this suggesting some additional change(s)? Such as adjusting other references to `prisma.nameChange` that include `reviewContext` outside of `ApproveNameChangeService`?

**Comment by psikoi** [comment]
> Is this suggesting some additional change(s)? Such as adjusting other references to prisma.nameChange that include reviewContext outside of ApproveNameChangeService?

Nope, the two changes you mentioned should be sufficient

1 - set to null when approved
2 - write a test that creates a name change, populates that column, approves the name change, assert if it's now null
