### ISSUE TITLE
newStats in name change details is null for players not tracked yet

### ISSUE THREAD

**Issue by rorro** [wise-old-man/wise-old-man#1460]
When fetching name change details and the new name is not tracked on WOM yet, `newStats` will be null. This is because `newPlayer` only exists if the new name is tracked on WOM.
https://github.com/wise-old-man/wise-old-man/blob/fc5d4336dc08f03e3e9cf512a0df479c8ccfa682/server/src/api/modules/name-changes/services/FetchNameChangeDetailsService.ts#L141

**Comment by psikoi** [comment]
`newStats` can come from the `newPlayer.latestSnapshot` or by parsing the current hiscores of `newName`, so `newStats` could still exist even if `newPlayer` doesn't.

So the line of code you highlighted is wrong, instead of returning null when newPlayer doesn't exist, it should maybe be `formatSnapshot(newStats, getPlayerEfficiencyMap(newStats, oldPlayer))`, or the entire line could be rewritten to:

```typescript
// use oldPlayer if newPlayer is null
newStats: formatSnapshot(newStats, getPlayerEfficiencyMap(newStats, newPlayer ?? oldPlayer)) 
```

aka: format the new stats snapshot using oldPlayer's efficiency properties (type and build)
