### ISSUE TITLE
Multiple issues for the past few weeks.

### ISSUE THREAD

**Issue by HitachiB** [wise-old-man/wise-old-man#1578]
Hello, 

I'm looking for possible solutions to fix some issues I've been running into. First, WOM doesn't automatically update our group anymore. Nor does it update our competitions. We've had to manually update each and every member which is exhausting and time consuming. 

Another issue we're having is, when someone changes their name, it doesn't update and when we re-add the member with a name change, it automatically kicks them. Same goes for when adding new members. Most times we have to do it multiple times. 

Any assistance is greatly appreciated!

**Comment by rorro** [comment]
For the first point, it could be multiple reasons. Auto updating a group is a Patreon feature so it is possible that there is some issue with a Patreon subscription. Or a script using our API is broken.

Name changes are not automatic, they need to be reported to WOM [here](https://wiseoldman.net/names) for it to know it happened. Many name changes are automatically submitted by our [RuneLite plugin](https://runelite.net/plugin-hub/show/wom-utils). 

For further support, please join our Discord https://wiseoldman.net/discord.

**Comment by HitachiB** [comment]
That's not right. I do not have Patreon status and was able to update everything automatically up until a few weeks ago... Unless, it has changed to Patreon only a few weeks ago. 

Name changes have been automatic as well. As soon as a member changed their name, WOM automatically changed it and sent a notification to our discord.

**Comment by Sethmare** [comment]
Without more details it is hard to know exactly where the issue is, but group-wide auto-updates are reserved for Patreon subscribers. If your group was being updated automatically previously, it was likely due to another group member having Patreon perks, or possibly somebody had a script making updates requests via the API. Are you the only one who manages your group?

The name changes are reported to WOM either manually on the website, or through the WOM RuneLite plugin. The plugin goes through your friends list and reports name changes. There is no automated process outside of that.

For further support, please join our Discord where we can have a more private, in-depth conversation about your issue.

https://wiseoldman.net/discord.
