### ISSUE TITLE
Default sorting on "gained" tab

### ISSUE THREAD

**Issue by Sethmare** [wise-old-man/wise-old-man#472]
Suggestion:

Change the default sorting for the gained tab on an individual player to EHP/EHB, rank, or "gained" (I'm not sure which one would be best) instead of alphabetically.

Most likely, a user is going to be looking at that tab to see the skills/bosses/activities they have been working on recently, so it would make sense (to me) for one of those metrics to show up at the top.

**Current default sorting**:
![Screenshot_91](https://user-images.githubusercontent.com/66145237/98755155-3d3d9280-2385-11eb-9c24-a3a2bc8a62be.png)

**More relevant sorting**:
![Screenshot_92](https://user-images.githubusercontent.com/66145237/98755156-3dd62900-2385-11eb-8361-8c982846a975.png)

**Comment by psikoi** [comment]
Although I recognize that showing relevant data first is useful, I personally prefer the **default order** to be consistent, aka each line be where you expect it to be, and in this case that means keeping the same order as the OSRS hiscores and having them ordered alphabetically, which makes it easier to find.

Also, you can do that with just one click on the column header, and that's why it's there, to allow for customization.

But i'm open to other opinions.

**Comment by psikoi** [comment]
No updates on this, no one seems to hace an alternate opinion, closing for now.
