### ISSUE TITLE
Incorrect level calculations

### ISSUE THREAD

**Issue by psikoi** [wise-old-man/wise-old-man#505]
Apparently our `getLevel` function in `server/src/api/util/levels.ts` is wrong.

**getLevel(174)** should be 3 (currently 2)
**getLevel(1154)** should be 10 (currently 9)

This affect build detection for 10hp pures

**Comment by jolampi** [comment]
Looking at the [experience formula](https://oldschool.runescape.wiki/w/Experience#Formula) shows that dividing by 4 is only supposed to happen at the very end. Currently this same division is done during each call to the `getXpDifferenceTo` function, but the issue is actually hidden by the fact that the remainder is also returned. Most of the time this seems to yield the correct result in the end, but there are some corner cases where the decimal part breaks things.

The easiest solution is to simply account for the remainder and change [this condition](https://github.com/wise-old-man/wise-old-man/blob/ee4fa51743dc11e79c3c61a81024d4b8d8499a4d/server/src/api/util/level.ts#L25) to `(exp >= Math.floor(accumulated) && exp < Math.floor(accumulated + required))`. As the remainder issue still remains however, one should at least consider using a lookup table instead to always get veritably correct values.

PS. The same code also seems to be in `/app/src/utils/levels.js`.

PPS. Oddly enough, it seems like the xp remainder formula on that same wiki article is also incorrect for this reason. However, there seems to be a bit more going on, as the result from the exponent calculation is immediately rounded down which seems a bit questionable.

**Comment by psikoi** [comment]
> one should at least consider using a lookup table instead to always get veritably correct values.

The initial implementation had a lookup table, but somewhere along the way someone (can't remember who) changed it and it seemed to work fine until now
