### ISSUE TITLE
Sorting issue on Group "gained" interface

### ISSUE THREAD

**Issue by Sethmare** [wise-old-man/wise-old-man#634]
This one is a bit hard to show, but here goes.

It looks like the sorting gets messed up when showing the full list of group members in gains. It seems to work normally until you scroll far enough down that more member names start to load.

If you look at the arrows next to "gained" you can tell how I have decided to sort the members.

![Screenshot_74](https://user-images.githubusercontent.com/66145237/106233148-0ff9c700-61b3-11eb-8534-3b3717cfbbd0.png)
![Screenshot_75](https://user-images.githubusercontent.com/66145237/106233149-0ff9c700-61b3-11eb-8d63-f99df47cc2ec.png)
![Screenshot_76](https://user-images.githubusercontent.com/66145237/106233151-10925d80-61b3-11eb-843e-a3ab257f05d7.png)
![Screenshot_77](https://user-images.githubusercontent.com/66145237/106233153-10925d80-61b3-11eb-9141-1b98b3002e0d.png)

**Comment by Aluminoti** [comment]
I'm unsure if there is some sort of priority queue for issues but I'd like to express additional interest in getting this bug resolved.

We are quickly approaching the new year. Using the overall xp gained, kills gained, or some other metrics are great for pruning inactive members. Unfortunately, because of this issue, it makes it very difficult to do something like this.

As previously stated; Any group larger than 50 (requires a scroll for more members to load) will end up running into an issue when trying to use the sorting options.

**Comment by psikoi** [comment]
This table is no longer sortable on the new v2 app, exactly to prevent these issues with pagination. Closing.
