### ISSUE TITLE
Add additional roles to role dropdown in groups

### ISSUE THREAD

**Issue by ianloomis** [wise-old-man/wise-old-man#662]
Allow us to have more customization within our group related to roles. I spoke with Psi about the following hierarchy:

Leader (have currently) > Staff/Mod/Co-Leader Title Here > Member (have currently) > Alt

They would appear by default in this order while loading the group. This will allow all of your leaders and co-leaders to be at top and any alt accounts of members will be on the bottom.

**Comment by BoomOSRS** [comment]
You could go with all cc ranks, and just have it set to 'member' by default if one is not set. Would be great if the plugin could automatically update the group from the clan setup screen.
Otherwise just Leader/Staff/Member would probably be sufficient for most clans

Additional options could be Alt, as mentioned above, and possibly Founder.

**Comment by psikoi** [comment]
We should probably wait to hear more about the clan update before considering this as it seems to be bringing quite a few interesting changes to CC ranks.

**Comment by psikoi** [comment]
Implemented n #830
