### ISSUE TITLE
Add "guest" rank

### ISSUE THREAD

**Issue by Sethmare** [wise-old-man/wise-old-man#974]
Suggestions from Geeving <@163306897783390208>

Add "guest" icon and rank to the list of ranks available to assign to group members.

**Comment by psikoi** [comment]
@rorro What was the consensus on this?

**Comment by rorro** [comment]
Since there isn't an assignable `guest` rank in-game, we don't have a good way of implementing this. The best we could do is just add a guest role on WOM that can be manually set. If a player is assigned the guest role but isn't in the in-game clan, their role will be overwritten to `member` by the sync feature because the plugin overwrites the roles as well.

I wouldn't be against adding an assignable guest rank though, that part wouldn't be too hard. But anything that has to do with automatically syncing in-game clan guests is not feasible.

**Comment by psikoi** [comment]
I'll close this unless there's a decent (and practical) solution.
