### ISSUE TITLE
Default rank for non-clan group members

### ISSUE THREAD

**Issue by Sethmare** [wise-old-man/wise-old-man#975]
Suggestion: Allow group leaders to choose a default rank for members that get added without a specified rank

**Comment by psikoi** [comment]
I'm not sure what this means 🤔  @Sethmare do you remember?

**Comment by rorro** [comment]
In several places when, such as [when creating a group](https://github.com/wise-old-man/wise-old-man/blob/1d2b801db39a7a995df4b18688b71030c5141956/server/src/api/modules/groups/services/CreateGroupService.ts#L30) we default the group role to `member` if none is provided. The suggestion here is to make it configurable per group instead of defaulting to member.

**Comment by psikoi** [comment]
Ah I see, this seems not very worth it. Closing until it becomes relevant again.

**Comment by Sethmare** [comment]
Sorry I just saw this. What @rorro said haha
